version: '2'

volumes:
  dr-elephant-logs:
    external: false

services: 
 dr-elephant:
  build: 
    context: frontend/.
  ports: 
  - 8080:8080
  stdin_open: true
  volumes:
  - ./hadoop-conf:/usr/local/hadoop/etc/hadoop/
  - dr-elephant-logs:/usr/dr-elephant/logs
  - ./frontend/elephant.conf:/usr/dr-elephant/app-conf/elephant.conf
  - ./data/setup.sql:/usr/dr-elephant-data/setup.sql
